<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb6d000aac8faf14cfcaad4637f9fc0ee
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Cleanup_Action_Scheduler\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Cleanup_Action_Scheduler\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb6d000aac8faf14cfcaad4637f9fc0ee::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb6d000aac8faf14cfcaad4637f9fc0ee::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb6d000aac8faf14cfcaad4637f9fc0ee::$classMap;

        }, null, ClassLoader::class);
    }
}
