<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Cleanup_Action_Scheduler\\' => array($baseDir . '/core'),
);
